// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_example.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "response_example.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class request_example_res_tDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<request_example_res_t> {
} _request_example_res_t_default_instance_;

namespace protobuf_response_5fexample_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, error_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, error_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, return_data_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(request_example_res_t)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_request_example_res_t_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "response_example.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _request_example_res_t_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _request_example_res_t_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\026response_example.proto\"T\n\025request_exam"
      "ple_res_t\022\022\n\nerror_code\030\001 \001(\005\022\022\n\nerror_i"
      "nfo\030\002 \001(\t\022\023\n\013return_data\030\003 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 118);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "response_example.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_response_5fexample_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int request_example_res_t::kErrorCodeFieldNumber;
const int request_example_res_t::kErrorInfoFieldNumber;
const int request_example_res_t::kReturnDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

request_example_res_t::request_example_res_t()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_response_5fexample_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:request_example_res_t)
}
request_example_res_t::request_example_res_t(const request_example_res_t& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.error_info().size() > 0) {
    error_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_info_);
  }
  return_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.return_data().size() > 0) {
    return_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.return_data_);
  }
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:request_example_res_t)
}

void request_example_res_t::SharedCtor() {
  error_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_code_ = 0;
  _cached_size_ = 0;
}

request_example_res_t::~request_example_res_t() {
  // @@protoc_insertion_point(destructor:request_example_res_t)
  SharedDtor();
}

void request_example_res_t::SharedDtor() {
  error_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void request_example_res_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* request_example_res_t::descriptor() {
  protobuf_response_5fexample_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_response_5fexample_2eproto::file_level_metadata[0].descriptor;
}

const request_example_res_t& request_example_res_t::default_instance() {
  protobuf_response_5fexample_2eproto::InitDefaults();
  return *internal_default_instance();
}

request_example_res_t* request_example_res_t::New(::google::protobuf::Arena* arena) const {
  request_example_res_t* n = new request_example_res_t;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void request_example_res_t::Clear() {
// @@protoc_insertion_point(message_clear_start:request_example_res_t)
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_code_ = 0;
}

bool request_example_res_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:request_example_res_t)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string error_info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error_info()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->error_info().data(), this->error_info().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_example_res_t.error_info"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string return_data = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_return_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->return_data().data(), this->return_data().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_example_res_t.return_data"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:request_example_res_t)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:request_example_res_t)
  return false;
#undef DO_
}

void request_example_res_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:request_example_res_t)
  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // string error_info = 2;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), this->error_info().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.error_info");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->error_info(), output);
  }

  // string return_data = 3;
  if (this->return_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->return_data().data(), this->return_data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.return_data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->return_data(), output);
  }

  // @@protoc_insertion_point(serialize_end:request_example_res_t)
}

::google::protobuf::uint8* request_example_res_t::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:request_example_res_t)
  // int32 error_code = 1;
  if (this->error_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error_code(), target);
  }

  // string error_info = 2;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), this->error_info().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.error_info");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->error_info(), target);
  }

  // string return_data = 3;
  if (this->return_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->return_data().data(), this->return_data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.return_data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->return_data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:request_example_res_t)
  return target;
}

size_t request_example_res_t::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:request_example_res_t)
  size_t total_size = 0;

  // string error_info = 2;
  if (this->error_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->error_info());
  }

  // string return_data = 3;
  if (this->return_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->return_data());
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void request_example_res_t::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:request_example_res_t)
  GOOGLE_DCHECK_NE(&from, this);
  const request_example_res_t* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const request_example_res_t>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:request_example_res_t)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:request_example_res_t)
    MergeFrom(*source);
  }
}

void request_example_res_t::MergeFrom(const request_example_res_t& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:request_example_res_t)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.error_info().size() > 0) {

    error_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_info_);
  }
  if (from.return_data().size() > 0) {

    return_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.return_data_);
  }
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void request_example_res_t::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:request_example_res_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void request_example_res_t::CopyFrom(const request_example_res_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:request_example_res_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool request_example_res_t::IsInitialized() const {
  return true;
}

void request_example_res_t::Swap(request_example_res_t* other) {
  if (other == this) return;
  InternalSwap(other);
}
void request_example_res_t::InternalSwap(request_example_res_t* other) {
  error_info_.Swap(&other->error_info_);
  return_data_.Swap(&other->return_data_);
  std::swap(error_code_, other->error_code_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata request_example_res_t::GetMetadata() const {
  protobuf_response_5fexample_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_response_5fexample_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// request_example_res_t

// int32 error_code = 1;
void request_example_res_t::clear_error_code() {
  error_code_ = 0;
}
::google::protobuf::int32 request_example_res_t::error_code() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_code)
  return error_code_;
}
void request_example_res_t::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:request_example_res_t.error_code)
}

// string error_info = 2;
void request_example_res_t::clear_error_info() {
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& request_example_res_t::error_info() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_info)
  return error_info_.GetNoArena();
}
void request_example_res_t::set_error_info(const ::std::string& value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.error_info)
}
#if LANG_CXX11
void request_example_res_t::set_error_info(::std::string&& value) {
  
  error_info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_example_res_t.error_info)
}
#endif
void request_example_res_t::set_error_info(const char* value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.error_info)
}
void request_example_res_t::set_error_info(const char* value, size_t size) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.error_info)
}
::std::string* request_example_res_t::mutable_error_info() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.error_info)
  return error_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* request_example_res_t::release_error_info() {
  // @@protoc_insertion_point(field_release:request_example_res_t.error_info)
  
  return error_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void request_example_res_t::set_allocated_error_info(::std::string* error_info) {
  if (error_info != NULL) {
    
  } else {
    
  }
  error_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_info);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.error_info)
}

// string return_data = 3;
void request_example_res_t::clear_return_data() {
  return_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& request_example_res_t::return_data() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.return_data)
  return return_data_.GetNoArena();
}
void request_example_res_t::set_return_data(const ::std::string& value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.return_data)
}
#if LANG_CXX11
void request_example_res_t::set_return_data(::std::string&& value) {
  
  return_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_example_res_t.return_data)
}
#endif
void request_example_res_t::set_return_data(const char* value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.return_data)
}
void request_example_res_t::set_return_data(const char* value, size_t size) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.return_data)
}
::std::string* request_example_res_t::mutable_return_data() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.return_data)
  return return_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* request_example_res_t::release_return_data() {
  // @@protoc_insertion_point(field_release:request_example_res_t.return_data)
  
  return return_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void request_example_res_t::set_allocated_return_data(::std::string* return_data) {
  if (return_data != NULL) {
    
  } else {
    
  }
  return_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), return_data);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.return_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
