// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_example.proto

#ifndef PROTOBUF_response_5fexample_2eproto__INCLUDED
#define PROTOBUF_response_5fexample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_response_5fexample_2eproto();
void protobuf_AssignDesc_response_5fexample_2eproto();
void protobuf_ShutdownFile_response_5fexample_2eproto();

class request_example_res_t;

// ===================================================================

class request_example_res_t : public ::google::protobuf::Message {
 public:
  request_example_res_t();
  virtual ~request_example_res_t();

  request_example_res_t(const request_example_res_t& from);

  inline request_example_res_t& operator=(const request_example_res_t& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const request_example_res_t& default_instance();

  void Swap(request_example_res_t* other);

  // implements Message ----------------------------------------------

  inline request_example_res_t* New() const { return New(NULL); }

  request_example_res_t* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const request_example_res_t& from);
  void MergeFrom(const request_example_res_t& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(request_example_res_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // optional string error_info = 2;
  void clear_error_info();
  static const int kErrorInfoFieldNumber = 2;
  const ::std::string& error_info() const;
  void set_error_info(const ::std::string& value);
  void set_error_info(const char* value);
  void set_error_info(const char* value, size_t size);
  ::std::string* mutable_error_info();
  ::std::string* release_error_info();
  void set_allocated_error_info(::std::string* error_info);

  // optional string return_data = 3;
  void clear_return_data();
  static const int kReturnDataFieldNumber = 3;
  const ::std::string& return_data() const;
  void set_return_data(const ::std::string& value);
  void set_return_data(const char* value);
  void set_return_data(const char* value, size_t size);
  ::std::string* mutable_return_data();
  ::std::string* release_return_data();
  void set_allocated_return_data(::std::string* return_data);

  // @@protoc_insertion_point(class_scope:request_example_res_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr error_info_;
  ::google::protobuf::internal::ArenaStringPtr return_data_;
  ::google::protobuf::int32 error_code_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_response_5fexample_2eproto();
  friend void protobuf_AssignDesc_response_5fexample_2eproto();
  friend void protobuf_ShutdownFile_response_5fexample_2eproto();

  void InitAsDefaultInstance();
  static request_example_res_t* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// request_example_res_t

// optional int32 error_code = 1;
inline void request_example_res_t::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 request_example_res_t::error_code() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_code)
  return error_code_;
}
inline void request_example_res_t::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:request_example_res_t.error_code)
}

// optional string error_info = 2;
inline void request_example_res_t::clear_error_info() {
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& request_example_res_t::error_info() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_info)
  return error_info_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void request_example_res_t::set_error_info(const ::std::string& value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.error_info)
}
inline void request_example_res_t::set_error_info(const char* value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.error_info)
}
inline void request_example_res_t::set_error_info(const char* value, size_t size) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.error_info)
}
inline ::std::string* request_example_res_t::mutable_error_info() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.error_info)
  return error_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* request_example_res_t::release_error_info() {
  
  return error_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void request_example_res_t::set_allocated_error_info(::std::string* error_info) {
  if (error_info != NULL) {
    
  } else {
    
  }
  error_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_info);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.error_info)
}

// optional string return_data = 3;
inline void request_example_res_t::clear_return_data() {
  return_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& request_example_res_t::return_data() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.return_data)
  return return_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void request_example_res_t::set_return_data(const ::std::string& value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.return_data)
}
inline void request_example_res_t::set_return_data(const char* value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.return_data)
}
inline void request_example_res_t::set_return_data(const char* value, size_t size) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.return_data)
}
inline ::std::string* request_example_res_t::mutable_return_data() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.return_data)
  return return_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* request_example_res_t::release_return_data() {
  
  return return_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void request_example_res_t::set_allocated_return_data(::std::string* return_data) {
  if (return_data != NULL) {
    
  } else {
    
  }
  return_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), return_data);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.return_data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_response_5fexample_2eproto__INCLUDED
