// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_example.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "response_example.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* request_example_res_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  request_example_res_t_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_response_5fexample_2eproto() {
  protobuf_AddDesc_response_5fexample_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "response_example.proto");
  GOOGLE_CHECK(file != NULL);
  request_example_res_t_descriptor_ = file->message_type(0);
  static const int request_example_res_t_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, error_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, error_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, return_data_),
  };
  request_example_res_t_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      request_example_res_t_descriptor_,
      request_example_res_t::default_instance_,
      request_example_res_t_offsets_,
      -1,
      -1,
      -1,
      sizeof(request_example_res_t),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_example_res_t, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_response_5fexample_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      request_example_res_t_descriptor_, &request_example_res_t::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_response_5fexample_2eproto() {
  delete request_example_res_t::default_instance_;
  delete request_example_res_t_reflection_;
}

void protobuf_AddDesc_response_5fexample_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026response_example.proto\"T\n\025request_exam"
    "ple_res_t\022\022\n\nerror_code\030\001 \001(\005\022\022\n\nerror_i"
    "nfo\030\002 \001(\t\022\023\n\013return_data\030\003 \001(\tb\006proto3", 118);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "response_example.proto", &protobuf_RegisterTypes);
  request_example_res_t::default_instance_ = new request_example_res_t();
  request_example_res_t::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_response_5fexample_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_response_5fexample_2eproto {
  StaticDescriptorInitializer_response_5fexample_2eproto() {
    protobuf_AddDesc_response_5fexample_2eproto();
  }
} static_descriptor_initializer_response_5fexample_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int request_example_res_t::kErrorCodeFieldNumber;
const int request_example_res_t::kErrorInfoFieldNumber;
const int request_example_res_t::kReturnDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

request_example_res_t::request_example_res_t()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:request_example_res_t)
}

void request_example_res_t::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

request_example_res_t::request_example_res_t(const request_example_res_t& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:request_example_res_t)
}

void request_example_res_t::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  error_code_ = 0;
  error_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

request_example_res_t::~request_example_res_t() {
  // @@protoc_insertion_point(destructor:request_example_res_t)
  SharedDtor();
}

void request_example_res_t::SharedDtor() {
  error_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void request_example_res_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* request_example_res_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return request_example_res_t_descriptor_;
}

const request_example_res_t& request_example_res_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_response_5fexample_2eproto();
  return *default_instance_;
}

request_example_res_t* request_example_res_t::default_instance_ = NULL;

request_example_res_t* request_example_res_t::New(::google::protobuf::Arena* arena) const {
  request_example_res_t* n = new request_example_res_t;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void request_example_res_t::Clear() {
  error_code_ = 0;
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool request_example_res_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:request_example_res_t)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 error_code = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_error_info;
        break;
      }

      // optional string error_info = 2;
      case 2: {
        if (tag == 18) {
         parse_error_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error_info()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->error_info().data(), this->error_info().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_example_res_t.error_info"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_return_data;
        break;
      }

      // optional string return_data = 3;
      case 3: {
        if (tag == 26) {
         parse_return_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_return_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->return_data().data(), this->return_data().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_example_res_t.return_data"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:request_example_res_t)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:request_example_res_t)
  return false;
#undef DO_
}

void request_example_res_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:request_example_res_t)
  // optional int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // optional string error_info = 2;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), this->error_info().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.error_info");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->error_info(), output);
  }

  // optional string return_data = 3;
  if (this->return_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->return_data().data(), this->return_data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.return_data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->return_data(), output);
  }

  // @@protoc_insertion_point(serialize_end:request_example_res_t)
}

::google::protobuf::uint8* request_example_res_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:request_example_res_t)
  // optional int32 error_code = 1;
  if (this->error_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error_code(), target);
  }

  // optional string error_info = 2;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), this->error_info().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.error_info");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->error_info(), target);
  }

  // optional string return_data = 3;
  if (this->return_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->return_data().data(), this->return_data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_example_res_t.return_data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->return_data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:request_example_res_t)
  return target;
}

int request_example_res_t::ByteSize() const {
  int total_size = 0;

  // optional int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  // optional string error_info = 2;
  if (this->error_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->error_info());
  }

  // optional string return_data = 3;
  if (this->return_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->return_data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void request_example_res_t::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const request_example_res_t* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const request_example_res_t>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void request_example_res_t::MergeFrom(const request_example_res_t& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
  if (from.error_info().size() > 0) {

    error_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_info_);
  }
  if (from.return_data().size() > 0) {

    return_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.return_data_);
  }
}

void request_example_res_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void request_example_res_t::CopyFrom(const request_example_res_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool request_example_res_t::IsInitialized() const {

  return true;
}

void request_example_res_t::Swap(request_example_res_t* other) {
  if (other == this) return;
  InternalSwap(other);
}
void request_example_res_t::InternalSwap(request_example_res_t* other) {
  std::swap(error_code_, other->error_code_);
  error_info_.Swap(&other->error_info_);
  return_data_.Swap(&other->return_data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata request_example_res_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = request_example_res_t_descriptor_;
  metadata.reflection = request_example_res_t_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// request_example_res_t

// optional int32 error_code = 1;
void request_example_res_t::clear_error_code() {
  error_code_ = 0;
}
 ::google::protobuf::int32 request_example_res_t::error_code() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_code)
  return error_code_;
}
 void request_example_res_t::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:request_example_res_t.error_code)
}

// optional string error_info = 2;
void request_example_res_t::clear_error_info() {
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& request_example_res_t::error_info() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.error_info)
  return error_info_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void request_example_res_t::set_error_info(const ::std::string& value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.error_info)
}
 void request_example_res_t::set_error_info(const char* value) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.error_info)
}
 void request_example_res_t::set_error_info(const char* value, size_t size) {
  
  error_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.error_info)
}
 ::std::string* request_example_res_t::mutable_error_info() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.error_info)
  return error_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* request_example_res_t::release_error_info() {
  
  return error_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void request_example_res_t::set_allocated_error_info(::std::string* error_info) {
  if (error_info != NULL) {
    
  } else {
    
  }
  error_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_info);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.error_info)
}

// optional string return_data = 3;
void request_example_res_t::clear_return_data() {
  return_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& request_example_res_t::return_data() const {
  // @@protoc_insertion_point(field_get:request_example_res_t.return_data)
  return return_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void request_example_res_t::set_return_data(const ::std::string& value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_example_res_t.return_data)
}
 void request_example_res_t::set_return_data(const char* value) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_example_res_t.return_data)
}
 void request_example_res_t::set_return_data(const char* value, size_t size) {
  
  return_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_example_res_t.return_data)
}
 ::std::string* request_example_res_t::mutable_return_data() {
  
  // @@protoc_insertion_point(field_mutable:request_example_res_t.return_data)
  return return_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* request_example_res_t::release_return_data() {
  
  return return_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void request_example_res_t::set_allocated_return_data(::std::string* return_data) {
  if (return_data != NULL) {
    
  } else {
    
  }
  return_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), return_data);
  // @@protoc_insertion_point(field_set_allocated:request_example_res_t.return_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
